services:
  os161:
    image: os161-env:saved
    platform: linux/amd64
    container_name: os161-dev
    stdin_open: true
    tty: true
    working_dir: /root/cs350-os161
    volumes:
      - os161-data:/root/cs350-os161
      - ./os161:/host/os161

volumes:
  os161-data: