services:
  os161:
    image: os161-env:saved
    platform: linux/amd64
    container_name: os161-dev
    stdin_open: true
    tty: true
    environment:
      - MAKESYSPATH=/root/cs350-os161/bmake/mk
    working_dir: /root/cs350-os161
    volumes:
      - ./os161:/root/cs350-os161